# Generated by Django 4.2 on 2023-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_service_comments_service_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
