# Generated by Django 4.2 on 2023-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_service_duration_alter_service_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='service',
            name='likes',
        ),
    ]
