# Generated by Django 4.2 on 2023-05-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0004_remove_service_comments_remove_service_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='likes',
            field=models.ManyToManyField(related_name='liked_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='salon.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
